version: '3.8'

services:
  api:
    container_name: synchrona-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}