version: '3.8'

services:
  api:
    container_name: synchrona-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
      - MINUTE_CRON=${MINUTE_CRON} 
      - HOUR_CRON=${HOUR_CRON}
      - DAY_CRON=${DAY_CRON}
      - MONTH_CRON=${MONTH_CRON}
      - YEAR_CRON=${YEAR_CRON}
    ports:
      - ${PORT}:${PORT}